import type { PlanetContent } from "./types";

export const ganymede: PlanetContent = {
  id: "ganymede",
  tagline: "The largest moon in the solar system, bigger than Mercury, with its own magnetic field and a hidden salty ocean.",
  intro: [
    "Ganymede is the largest moon in the solar system and the third of Jupiter's four Galilean moons counting outward. With a radius of 2,634 km it is about 8% wider than the planet Mercury, though only 45% as massive, because it is made of roughly equal parts rock and water ice. It orbits Jupiter every 7.15 days at a distance of about 1,070,000 km, tidally locked with one face always turned towards the planet.",
    "Ganymede is a planet in all but orbit. It has fully separated into a liquid iron core, a rocky mantle and a thick outer layer of ice and water, and its core generates a magnetic field, something no other moon is known to do. Beneath perhaps 150 km of ice lies a salty ocean that may hold more water than all of Earth's oceans combined, first inferred from NASA's Galileo orbiter in the late 1990s and confirmed by Hubble Space Telescope observations of the moon's aurorae in 2015.",
    "Its surface tells a two-part story: dark, ancient, heavily cratered regions cover about a third of it, while the rest is brighter, younger terrain scored by long parallel grooves and ridges left by tectonic activity billions of years ago. Ganymede is now the primary target of ESA's Juice mission, which launched in April 2023, reaches Jupiter in July 2031 and in December 2034 will become the first spacecraft ever to orbit a moon other than our own.",
  ],
  sections: [
    {
      title: "Structure and interior: a fully differentiated world",
      paragraphs: [
        "Galileo's gravity measurements gave Ganymede the lowest moment of inertia factor of any solid body in the solar system, about 0.31, which means its mass is strongly concentrated towards the centre. That is the signature of complete differentiation: a dense metallic core, a silicate mantle around it and a thick, low-density shell of water ice and liquid water on the outside. Models place the liquid iron and iron-sulphide core at a radius of perhaps 500 km or somewhat more, depending on how much sulphur it contains, with a rocky mantle extending to roughly 800 km below the surface.",
        "Above the rock lies about 800 km of water in various forms. Near the top is a rigid ice crust, and beneath it a salty ocean; the 2015 Hubble study suggested a crust about 150 km thick over an ocean some 100 km deep, though the numbers are model-dependent. Because the water layer is so deep, pressures at the bottom are high enough to freeze water into dense forms of ice that sink rather than float. A 2014 NASA study proposed a club-sandwich structure, with several ocean layers separated by sheets of high-pressure ice, and possibly a lowest layer of liquid in contact with the rocky seafloor, which would matter for any chemistry relevant to life.",
        "The magnetic field is the most surprising consequence of this structure. Galileo discovered it on its first close flyby in June 1996: a permanent dipole with a strength of about 720 nanotesla at the equator, several times the strength of Jupiter's own field at that distance and about three times Mercury's magnetic moment. It is almost certainly generated by convection in the liquid iron core, as Earth's is. Why such a small body still has a molten, churning core is not fully understood; past episodes of stronger tidal heating, when the moon's orbit passed through other resonances, may have kept it warm.",
      ],
      highlight: "Ganymede is the only moon known to generate its own magnetic field, carving out a tiny magnetosphere inside Jupiter's.",
    },
    {
      title: "Surface and geology: dark cratered terrain and bright grooves",
      paragraphs: [
        "About a third of Ganymede's surface is dark terrain, the largest expanse being Galileo Regio, a region nearly 3,000 km across. These areas are saturated with craters and are thought to be around four billion years old, close to the age of the moon itself. They are crossed by furrows, long arc-shaped troughs that may be the remains of enormous ancient impact basins. The dark colour comes from a thin lag of rocky and carbon-rich material left behind as ice sublimated away over the ages.",
        "The remaining two-thirds is bright terrain, cut by swathes of parallel grooves and ridges, known as sulci, hundreds of kilometres long and typically a few hundred metres high. Galileo's close-up images showed that they are tectonic, produced by extension: the icy crust was stretched and broke along faults, and older surfaces were pulled apart and rearranged. The bright terrain is younger, with fewer craters, but still probably one to two billion years old. Whether liquid water or slush ever flooded the grooves, a form of cryovolcanism, is uncertain; the modern view is that tectonics did most of the work.",
        "Ganymede's craters are flatter than those on rocky worlds because the icy crust slowly relaxes and flows. The oldest have collapsed into bright circular patches called palimpsests, ghosts of the original craters. The largest surviving impact structure, Gilgamesh, is a multi-ring basin nearly 600 km across in the southern hemisphere. Bright rays around younger craters show where fresh, clean ice was thrown out across the darker surface.",
      ],
      highlight: "Two-thirds of Ganymede is bright, grooved terrain shaped by tectonic stretching; the dark third is about four billion years old.",
    },
    {
      title: "A tenuous oxygen atmosphere and polar aurorae",
      paragraphs: [
        "Ganymede has an extremely thin atmosphere of molecular oxygen, first identified with the Hubble Space Telescope in the 1990s, with a surface pressure of only about 0.2 to 1.2 micropascals, around a hundred-billionth of Earth's. Like Europa's, it is produced not by life but by radiation: charged particles from Jupiter's magnetosphere split water ice into hydrogen, which escapes, and oxygen, which lingers. Hubble observations reported in 2021 also found evidence of water vapour, sublimating from the ice near the equator around noon. Ganymede's ionosphere was detected by Galileo and by Juno.",
        "The moon's own magnetic field reshapes this environment. It creates a miniature magnetosphere four to five Ganymede radii across, embedded inside Jupiter's, with closed field lines near the equator that trap charged particles and open field lines at high latitudes that connect straight to Jupiter. Along those open lines, electrons rain onto the polar regions, exciting the oxygen atmosphere into aurorae, glowing ovals around each pole that Hubble can see in ultraviolet light.",
        "Those aurorae are what revealed the ocean. Because Jupiter's field rocks back and forth over Ganymede every ten hours, the auroral ovals should sway by about six degrees; a salty, electrically conducting ocean generates an induced field that damps the motion. Hubble measured a sway of only about two degrees, matching the ocean model. The magnetic shielding also matters for the surface: in 2023 Juno's infrared spectrometer found that salts and organic compounds, including hydrated sodium chloride, ammonium chloride and sodium carbonate, are concentrated at low latitudes, where the field protects them from radiation. They may be traces of the ocean brought up in the past.",
      ],
    },
    {
      title: "Orbit, tides and the Laplace resonance",
      paragraphs: [
        "Ganymede orbits Jupiter every 7.155 days on an almost circular path, with an eccentricity of just 0.0013 and an inclination of only 0.2 degrees. It is tidally locked, so a Ganymede day equals its orbital period. Together with Io and Europa it forms the Laplace resonance: for every orbit of Ganymede, Europa completes exactly two and Io exactly four. The three moons periodically line up, and their repeated tugs keep all three orbits slightly elliptical.",
        "Ganymede is the outermost member of the resonance and the one least affected by it. Its small forced eccentricity means that tidal heating today is modest compared with Io or Europa, and radioactive decay in its rocky interior is thought to be its main internal heat source now. But the resonance may not always have been so gentle. Models suggest that as the moons' orbits evolved, Ganymede passed through stronger resonances that pumped up its eccentricity and its tidal heating for a while, which could explain both the ancient tectonic reworking of the bright terrain and the persistence of a liquid core capable of generating a magnetic field.",
        "Callisto, further out, is not part of the resonance, and the contrast is instructive: it is nearly the same size as Ganymede but never differentiated fully, has no magnetic field and shows no sign of tectonic activity. Ganymede's dynamic history seems to owe a great deal to its orbital relationship with its inner neighbours.",
      ],
      highlight: "Ganymede completes one orbit for every two of Europa and four of Io, a resonance that may have driven its ancient tectonics.",
    },
    {
      title: "Exploration and missions",
      paragraphs: [
        "Pioneer 10 returned the first close-up images of Ganymede on 3 December 1973, followed by Pioneer 11 in 1974. Voyager 1 and 2 flew through the Jupiter system in 1979 and mapped the moon well enough to reveal the two terrain types and the grooved landscape, and to fix its size; when Voyager 1 measured Titan's solid body the following year, Ganymede emerged as the largest moon in the solar system. NASA's Galileo orbiter made six close flybys between 1996 and 2000, discovering the magnetic field on the first of them, on 27 June 1996, imaging the surface at resolutions down to tens of metres and gathering the gravity and magnetic data that revealed the differentiated interior and hinted at the ocean.",
        "NASA's Juno spacecraft passed 1,038 km above Ganymede on 7 June 2021, the closest approach since Galileo in May 2000, and the flyby shortened Juno's orbit around Jupiter from 53 to 43 days. Juno photographed the surface, probed the ionosphere and magnetosphere, and its infrared spectrometer mapped the salts and organics reported in October 2023. Europa Clipper, launched in October 2024 and arriving at Jupiter in April 2030, will also use Ganymede for several gravity assists during its tour and is planned to end its mission by impacting the moon.",
        "The centrepiece is ESA's Jupiter Icy Moons Explorer, Juice, which launched on 14 April 2023 and arrives at Jupiter in July 2031. After a series of flybys of Ganymede, Callisto and Europa, it will enter orbit around Ganymede in December 2034, the first orbit of any moon other than Earth's. From an elliptical orbit and then a circular one 500 km up, Juice will map the surface, sound the ice with radar, measure the magnetic and gravity fields to pin down the ocean's depth and salinity, and study the magnetosphere, before the mission ends in 2035 with a planned impact on the surface.",
      ],
      highlight: "Juice reaches Jupiter in July 2031 and in December 2034 will become the first spacecraft to orbit a moon other than our own.",
    },
    {
      title: "Name and discovery",
      paragraphs: [
        "Ganymede was discovered by Galileo Galilei on 7 January 1610, on the first night he pointed his telescope at Jupiter. He saw three points of light in a line beside the planet, which turned out to be Ganymede, Callisto and the combined light of Io and Europa, and over the following week he watched them move and realised they were moons in orbit. Simon Marius, a German astronomer, said he had seen them independently at about the same time, and it was Marius, following a suggestion by Johannes Kepler, who gave the moons their mythological names in 1614.",
        "In Greek myth Ganymede was a beautiful Trojan prince whom Zeus, in the form of an eagle, carried off to Olympus to serve as cupbearer to the gods; he is the only one of the four namesakes who is not a female lover of Zeus. Galileo called the moons the Medicean Stars in honour of his patrons, the Medici, and for centuries astronomers used numbers instead: Ganymede was Jupiter III. The names Marius proposed only came into general use in the 20th century.",
        "There is even a claim of a pre-telescopic sighting. The Chinese astronomer Gan De recorded a faint star near Jupiter in 365 BC that may have been Ganymede, which at its brightest is just visible to a sharp naked eye if Jupiter's glare can be blocked. Whether he really saw it cannot be proved.",
      ],
    },
    {
      title: "What you'd experience there",
      paragraphs: [
        "Ganymede's surface gravity is 1.43 m/s², about 15% of Earth's, a little less than the Moon's, so you would bound across the surface with ease. Underfoot would be dirty water ice at about −160 °C, hard as granite, dusted with dark rocky material in the old terrain and cleaner and brighter in the grooved regions. A day, from one sunrise to the next, would last 7.15 Earth days, and the Sun would appear as a small, brilliant disc giving about one twenty-seventh of the light it does on Earth, still far brighter than a full Moon.",
        "From the hemisphere facing Jupiter the planet would hang motionless in the sky, nearly 8 degrees across, about 15 times the width of the full Moon as seen from Earth, its bands and storms clearly visible. Io, Europa and Callisto would be seen circling it. The sky would be black, since the oxygen atmosphere is far too thin to scatter light or carry sound, though at the poles a faint aurora might be visible in the long night.",
        "Radiation is the principal danger. Ganymede lies inside Jupiter's magnetosphere, and although its own field deflects some particles, the dose is still roughly 80 millisieverts a day, more than a hundred times what an astronaut receives on the International Space Station, so a long stay would require burrowing into the ice. Ganymede has nevertheless been discussed as a possible base because of its size, its water and its comparatively benign environment next to Io and Europa.",
      ],
      highlight: "From Ganymede, Jupiter spans 8 degrees of sky and never moves, and a single day lasts more than a week.",
    },
  ],
  layers: [
    {
      name: "Liquid iron core",
      description: "A molten core of iron and iron sulphide whose convection generates Ganymede's magnetic field, the only intrinsic field known at any moon.",
      color: "#c9a26a",
      radiusFraction: 0.25,
      detail: "Iron and iron sulphide, radius perhaps 500 to 700 km, model-dependent, about 1,200 to 1,400 °C",
    },
    {
      name: "Rocky mantle",
      description: "A silicate mantle, probably similar in composition to ordinary chondrite meteorites, extending to the base of the water layer about 800 km below the surface.",
      color: "#8f6a4a",
      radiusFraction: 0.7,
      detail: "Silicate rock, roughly 1,100 to 1,300 km thick",
    },
    {
      name: "Ocean and high-pressure ice",
      description: "A salty liquid-water ocean, perhaps 100 km deep, possibly split into several layers by sheets of dense high-pressure ice, with the deepest liquid perhaps touching rock.",
      color: "#2f6fb5",
      radiusFraction: 0.943,
      detail: "Salt water and dense ice phases, about 650 km in total; ocean layer roughly 100 km thick",
    },
    {
      name: "Ice crust",
      description: "A rigid shell of ordinary water ice, dark and cratered in the ancient regions and bright and grooved where tectonics reworked it.",
      color: "#d9dde3",
      radiusFraction: 1,
      detail: "Water ice, about 150 km thick; surface around −160 °C",
    },
  ],
  timeline: [
    { year: "1610", title: "Discovery", detail: "Galileo Galilei sees Ganymede on 7 January as one of the points of light beside Jupiter; Simon Marius later proposes its name." },
    { year: "1973", title: "Pioneer 10", detail: "The first spacecraft to reach Jupiter returns the first close-up images of Ganymede on 3 December." },
    { year: "1979", title: "Voyager flybys", detail: "Voyager 1 and 2 map the dark and bright terrains and the grooved landscape and measure Ganymede precisely for the first time." },
    { year: "1996", title: "Magnetic field found", detail: "On its first close flyby, on 27 June, NASA's Galileo discovers that Ganymede generates its own magnetic field." },
    { year: "1996–2000", title: "Galileo flybys", detail: "Six close passes reveal a fully differentiated interior and induced magnetic signals hinting at a salty ocean." },
    { year: "2014", title: "Club-sandwich model", detail: "A NASA study proposes that Ganymede's water layer may be stacked into several oceans separated by high-pressure ice." },
    { year: "2015", title: "Ocean confirmed", detail: "Hubble observations of the swaying aurorae, published in March, show an ocean about 100 km deep beneath roughly 150 km of ice." },
    { year: "2021", title: "Juno flyby", detail: "On 7 June Juno passes 1,038 km above Ganymede, the closest approach since 2000, imaging the surface and probing its magnetosphere." },
    { year: "2023", title: "Juice launches; salts found", detail: "ESA's Juice lifts off on 14 April; in October Juno's infrared data reveal salts and organic compounds on the surface." },
    { year: "2031", title: "Juice arrives", detail: "Juice is due to enter the Jupiter system in July and begin flybys of Ganymede, Callisto and Europa." },
    { year: "2034", title: "First moon orbiter", detail: "In December Juice is scheduled to enter orbit around Ganymede, the first spacecraft to orbit a moon other than Earth's, ending with an impact in 2035." },
  ],
  comparisons: [
    { label: "Diameter", value: 5268.2, earth: 12742, unit: "km" },
    { label: "Mass", value: 0.0248, earth: 1, unit: "× Earth" },
    { label: "Surface gravity", value: 1.428, earth: 9.81, unit: "m/s²" },
    { label: "Rotation period", value: 171.72, earth: 23.93, unit: "hours" },
    { label: "Mean temperature", value: -163, earth: 15, unit: "°C" },
    { label: "Escape velocity", value: 2.74, earth: 11.19, unit: "km/s" },
    { label: "Surface pressure", value: 1e-11, earth: 1.013, unit: "bar" },
  ],
  moons: [],
  quiz: [
    {
      prompt: "What makes Ganymede unique among all known moons?",
      options: ["It has a thick nitrogen atmosphere", "It generates its own magnetic field", "It orbits Jupiter backwards", "It has active volcanoes"],
      answer: "It generates its own magnetic field",
      explanation: "Galileo discovered in 1996 that Ganymede has an intrinsic magnetic field, almost certainly produced by convection in its liquid iron core.",
    },
    {
      prompt: "How does Ganymede compare in size with the planet Mercury?",
      options: ["It is about half Mercury's diameter", "It is about the same size as Mercury", "It is about 8% wider than Mercury but less than half as massive", "It is twice Mercury's diameter and mass"],
      answer: "It is about 8% wider than Mercury but less than half as massive",
      explanation: "Ganymede's diameter of 5,268 km beats Mercury's 4,879 km, but being half ice it has only about 45% of Mercury's mass.",
    },
    {
      prompt: "How did Hubble confirm Ganymede's subsurface ocean in 2015?",
      options: ["By photographing water plumes", "By measuring how little the aurorae sway as Jupiter's field rocks", "By detecting waves on the surface", "By seeing the ocean through cracks in the ice"],
      answer: "By measuring how little the aurorae sway as Jupiter's field rocks",
      explanation: "A conducting salty ocean generates an induced field that damps the motion of the auroral ovals from about six degrees to about two, exactly what Hubble saw.",
    },
    {
      prompt: "What will ESA's Juice spacecraft do in December 2034?",
      options: ["Land on Ganymede", "Enter orbit around Ganymede, the first orbit of a moon other than Earth's", "Fly past Pluto", "Return samples to Earth"],
      answer: "Enter orbit around Ganymede, the first orbit of a moon other than Earth's",
      explanation: "After arriving at Jupiter in July 2031 and making flybys of the icy moons, Juice will enter Ganymede orbit in December 2034 and study it until 2035.",
    },
    {
      prompt: "Which two kinds of terrain make up Ganymede's surface?",
      options: ["Volcanic plains and lava lakes", "Dark ancient cratered terrain and bright younger grooved terrain", "Sand dunes and dry riverbeds", "Methane seas and ice mountains"],
      answer: "Dark ancient cratered terrain and bright younger grooved terrain",
      explanation: "About a third of Ganymede is dark, heavily cratered terrain roughly four billion years old; the rest is brighter, tectonically grooved terrain.",
    },
  ],
  glossary: [
    { term: "Differentiation", definition: "The separation of a body into layers of different density, such as a metal core, rocky mantle and icy shell. Ganymede is fully differentiated." },
    { term: "Magnetosphere", definition: "The region around a body dominated by its magnetic field. Ganymede's is four to five times its radius across and sits inside Jupiter's." },
    { term: "Dynamo", definition: "The process by which convection in a liquid, electrically conducting core generates a magnetic field, as in Earth and Ganymede." },
    { term: "Sulci", definition: "The bands of parallel grooves and ridges that cross Ganymede's bright terrain, formed by stretching of the icy crust." },
    { term: "Palimpsest", definition: "A bright, flat circular patch left where an ancient crater has relaxed and flattened in Ganymede's slowly flowing ice." },
    { term: "High-pressure ice", definition: "Dense crystalline forms of water ice that form at great depth and can sink beneath liquid water, possibly splitting Ganymede's ocean into layers." },
    { term: "Laplace resonance", definition: "The 4:2:1 orbital lock between Io, Europa and Ganymede, which keeps their orbits slightly elliptical." },
    { term: "Aurora", definition: "Glowing bands of gas around a body's poles, excited by charged particles guided in along magnetic field lines. Ganymede's revealed its ocean." },
  ],
  sources: [
    { title: "NASA Science: Ganymede", url: "https://science.nasa.gov/jupiter/moons/ganymede/" },
    { title: "NSSDC Jovian Satellite Fact Sheet", url: "https://nssdc.gsfc.nasa.gov/planetary/factsheet/joviansatfact.html" },
    { title: "ESA: Juice (Jupiter Icy Moons Explorer)", url: "https://www.esa.int/Science_Exploration/Space_Science/Juice" },
    { title: "NASA JPL: Juno's Ganymede close-up (June 2021)", url: "https://www.jpl.nasa.gov/images/pia24681-junos-ganymede-close-up/" },
    { title: "NASA JPL: Salts and organics observed on Ganymede's surface by Juno (October 2023)", url: "https://www.jpl.nasa.gov/news/salts-and-organics-observed-on-ganymedes-surface-by-nasas-juno/" },
    { title: "Saur et al. 2015: The search for a subsurface ocean in Ganymede with Hubble observations of its auroral ovals", url: "https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2014ja020778" },
  ],
};
