import type { PlanetContent } from "./types";

export const sun: PlanetContent = {
  id: "sun",
  tagline: "A 4.6-billion-year-old fusion reactor that holds 99.8% of the solar system in its grip.",
  intro: [
    "The Sun is an ordinary star that happens to be ours. It is a G-type main-sequence star, a ball of mostly hydrogen and helium about 1.39 million km across, so large that roughly 1.3 million Earths could fit inside it. Every planet, moon, asteroid and comet in the solar system is a leftover from the disc of gas and dust that collapsed to form it about 4.6 billion years ago, and together they add up to just 0.2% of the system's mass. Everything else is the Sun.",
    "Deep in its core, at around 15 million °C, the Sun fuses about 600 million tonnes of hydrogen into helium every second. Roughly 4 million tonnes of that mass vanishes as pure energy, which is what lights and warms the Earth from 150 million km away. The light you see left the Sun's surface about 8 minutes and 20 seconds ago, but the energy behind it was released in the core roughly 100,000 years earlier, because photons take that long to fight their way out.",
    "The Sun is not a quiet, steady lamp. Its surface churns with convection cells the size of Texas, its magnetic field twists and snaps to produce sunspots, flares and coronal mass ejections, and its activity rises and falls on a roughly 11-year cycle. Understanding this behaviour is not just astronomy: solar storms can knock out satellites, power grids and radio communication here on Earth.",
  ],
  sections: [
    {
      title: "Structure and interior",
      paragraphs: [
        "Astronomers divide the Sun into layers by how energy travels through them. The core occupies the inner quarter of the radius but contains about half the Sun's mass, squeezed to 150 times the density of water. Here temperatures and pressures are high enough for protons to overcome their mutual repulsion and fuse, mostly through the proton-proton chain, releasing energy as gamma-ray photons and neutrinos.",
        "Above the core lies the radiative zone, extending to about 70% of the radius. Energy crosses it by radiation: photons are absorbed and re-emitted countless times by the dense plasma, taking a random walk that lasts on the order of 100,000 years (estimates range from tens of thousands to about 170,000 years). At the boundary with the next layer, called the tachocline, the rotation rate changes abruptly, and this shear is thought to be where the Sun's magnetic field is generated.",
        "In the convective zone, the outer 30% of the radius, the plasma is cool enough (below about 2 million °C) that it becomes opaque to radiation, so heat is carried instead by huge rising and sinking currents of gas, like water boiling in a pot. These currents reach the visible surface, the photosphere, where they appear as a seething pattern of granules about 1,000 km across, each lasting only 10 to 20 minutes.",
      ],
      highlight: "Light takes 8 minutes to reach Earth, but the energy behind it took around 100,000 years to escape the Sun's interior.",
    },
    {
      title: "The Sun's atmosphere",
      paragraphs: [
        "The photosphere, at about 5,500 °C, is the layer we see as the Sun's 'surface', although it is really just where the gas becomes transparent. It is only a few hundred kilometres thick. Sunspots appear here as darker patches where intense magnetic fields suppress convection and cool the gas to around 3,500 °C. They look dark only by contrast; an isolated sunspot would shine brighter than the full Moon.",
        "Above the photosphere lies the chromosphere, a few thousand kilometres of thinner, reddish gas visible briefly at the edge of a total solar eclipse. Then comes one of the Sun's great mysteries: the corona. This outermost atmosphere is extremely tenuous, yet its temperature soars above 1 million °C, hundreds of times hotter than the surface below it. Energy carried by magnetic waves and countless tiny 'nanoflares' is the leading explanation, and it is a central question for the Parker Solar Probe and Solar Orbiter missions.",
        "The corona does not end; it flows outward as the solar wind, a stream of charged particles moving at 400 to 800 km/s that fills the whole solar system and carves out a bubble called the heliosphere. Earth's magnetic field deflects most of it, but some particles spiral down onto the poles and light up the atmosphere as the aurora.",
      ],
      highlight: "The corona is hundreds of times hotter than the surface beneath it, and we still do not fully know why.",
    },
    {
      title: "Sunspots, flares and space weather",
      paragraphs: [
        "The Sun's magnetic field is generated by the motion of its electrically conducting plasma, and because the equator rotates faster than the poles (about 25 days versus 35 days), the field lines get wound up and tangled. Where bundles of field burst through the surface they create sunspots, which come and go on an approximately 11-year cycle. At solar maximum there may be over a hundred spots visible at once; at minimum the disc can be blank for months.",
        "When tangled field lines suddenly reconnect they release enormous energy as solar flares, bursts of X-rays and ultraviolet that reach Earth in 8 minutes and can disrupt radio signals. Flares are often accompanied by coronal mass ejections (CMEs), billion-tonne clouds of plasma hurled into space at speeds of 1,000 km/s or more. A CME aimed at Earth arrives one to three days later and can trigger geomagnetic storms.",
        "The largest storm on record, the Carrington Event of September 1859, set telegraph wires sparking and painted auroras as far south as the Caribbean. A comparable event today could damage satellites and transformers on a huge scale, which is why agencies now run continuous space-weather forecasts. In May 2024 a strong storm (rated G5, the top category) produced auroras seen at unusually low latitudes worldwide, a preview of activity around the peak of the current cycle, Solar Cycle 25, whose smoothed sunspot number peaked in October 2024 with high activity continuing through 2025.",
      ],
      highlight: "Solar Cycle 25 peaked in 2024 to 2025, producing the strongest geomagnetic storm in more than 20 years.",
    },
    {
      title: "Exploration and missions",
      paragraphs: [
        "Because the Sun is so bright and hot, exploring it means either watching from a safe distance or engineering spacecraft that can survive up close. NASA and ESA's SOHO has watched the Sun continuously since 1996, discovering thousands of comets along the way. NASA's Solar Dynamics Observatory (launched 2010) returns a high-definition image every few seconds, and the twin STEREO spacecraft (2006) gave the first views of the Sun from two vantage points at once.",
        "NASA's Parker Solar Probe, launched in 2018, is the first spacecraft to fly through the corona. On 24 December 2024 it passed just 6.1 million km from the photosphere at about 690,000 km/h, the fastest any human-made object has travelled, shielded by an 11-cm carbon-composite heat shield. It has repeated that record-setting orbit through 2025 and 2026, completing its 29th close approach on 4 September 2026, and following the 2026 Heliophysics Senior Review NASA has extended the mission into 2029.",
        "ESA's Solar Orbiter, launched in 2020, uses repeated Venus flybys to tilt its orbit out of the ecliptic plane. In 2025 it returned the first-ever clear images of the Sun's south pole, and a Venus flyby in December 2026 will tilt its orbit further to 24°. India's Aditya-L1 observatory (launched 2023) watches from the L1 Lagrange point, and ESA's Proba-3 pair of satellites, launched in December 2024, fly in precise formation so one casts an artificial eclipse shadow on the other, giving long, clear views of the inner corona.",
      ],
      highlight: "Parker Solar Probe has flown within 6.1 million km of the Sun's surface, closer than any spacecraft before it.",
    },
    {
      title: "Name, myth and history",
      paragraphs: [
        "Almost every culture has placed the Sun at the centre of its mythology: Ra in Egypt, Helios and later Apollo in Greece, Sol in Rome, Amaterasu in Japan and Inti for the Inca. The English word 'Sun' comes from Old English 'sunne', and the adjective 'solar' from the Latin 'sol'. The Sun has no official name beyond that, which is why astronomers simply call it the Sun.",
        "For most of history people assumed the Sun circled the Earth. Aristarchus of Samos proposed a Sun-centred model around 250 BCE, but the idea only took hold after Copernicus published his heliocentric theory in 1543 and Galileo, Kepler and Newton supplied the observations and physics. Galileo's sunspot drawings in the 1610s showed the Sun rotates and is not a perfect, unchanging sphere.",
        "What powered the Sun remained a puzzle into the 20th century; 19th-century physicists calculated that gravitational contraction could only keep it shining for tens of millions of years, far shorter than the age of Earth's rocks. Arthur Eddington suggested nuclear fusion in 1920, and Hans Bethe worked out the detailed reactions in 1939. Confirmation came in the 1960s to 2000s from experiments that detected solar neutrinos, ghostly particles produced directly by fusion in the core.",
      ],
    },
    {
      title: "The Sun's life story",
      paragraphs: [
        "The Sun formed about 4.6 billion years ago when part of a giant molecular cloud collapsed under its own gravity, possibly triggered by a nearby supernova. Most of the material fell into the centre and ignited; the rest flattened into a spinning disc from which the planets condensed. Since then the Sun has brightened by about 30%, and it continues to brighten by around 1% every 100 million years.",
        "It is now about halfway through its main-sequence life. In roughly 5 billion years the core's hydrogen will run out, the outer layers will swell, and the Sun will become a red giant more than 100 times its current size, probably swallowing Mercury and Venus and scorching Earth. It will then shed its outer layers as a glowing planetary nebula and leave behind a white dwarf about the size of Earth, which will cool for trillions of years.",
      ],
      highlight: "The Sun is halfway through a roughly 10-billion-year life; it will end as an Earth-sized white dwarf.",
    },
    {
      title: "What you'd experience there",
      paragraphs: [
        "There is no surface to stand on; the photosphere is a gas roughly a ten-thousandth as dense as Earth's air, and any spacecraft would vaporise long before reaching it. If you could somehow hover there, gravity would be 28 times Earth's: a 70 kg person would weigh the equivalent of nearly 2 tonnes. The 'ground' beneath you would be a boiling landscape of granules, each the size of a country, rising and sinking over minutes.",
        "The sky would not be black. You would be immersed in a blinding glare far brighter than anything on Earth, with the sunspots appearing as dim, dark islands. Sound would travel through the plasma, and the Sun genuinely rings like a bell with sound waves that helioseismologists use to probe its interior, although the frequencies, with periods of about 5 minutes, are far below anything a human ear could hear.",
        "The Sun spins once every 25 days at its equator, but because it is not solid there is no single day length; the poles take about 35 days. Its axis is tilted about 7° to the plane of Earth's orbit, which is why we get slightly better views of one solar pole and then the other over the course of a year.",
      ],
    },
  ],
  layers: [
    {
      name: "Core",
      description: "Where fusion happens. Hydrogen nuclei combine into helium, releasing the energy that powers the whole solar system.",
      color: "#fff6c2",
      radiusFraction: 0.25,
      detail: "Hydrogen and helium plasma, ~15 million °C, 150 times the density of water",
    },
    {
      name: "Radiative zone",
      description: "Energy crawls outward as photons are absorbed and re-emitted by dense plasma, a journey that takes around 100,000 years.",
      color: "#ffcf5c",
      radiusFraction: 0.7,
      detail: "Plasma, 7 million °C at the base falling to ~2 million °C at the top",
    },
    {
      name: "Convective zone",
      description: "Cooler, opaque gas carries heat to the surface in giant rising and sinking currents, like a boiling pot.",
      color: "#ff9d2e",
      radiusFraction: 0.98,
      detail: "Turbulent plasma, ~2 million °C down to ~5,500 °C",
    },
    {
      name: "Photosphere",
      description: "The visible 'surface', a few hundred kilometres thick, dappled with granules and sunspots. Above it lie the chromosphere and the million-degree corona.",
      color: "#ff6a00",
      radiusFraction: 1,
      detail: "~5,500 °C, only ~0.0001 times the density of Earth's air",
    },
  ],
  timeline: [
    { year: "1610s", title: "Galileo tracks sunspots", detail: "Telescope observations by Galileo, Scheiner and others show the Sun rotates and has a changing, blemished surface." },
    { year: "1859", title: "Carrington Event", detail: "Richard Carrington observes the first recorded solar flare; the geomagnetic storm that follows is the strongest known, setting telegraph equipment sparking." },
    { year: "1939", title: "Fusion explained", detail: "Hans Bethe describes the nuclear reactions that power the Sun, building on Eddington's 1920 suggestion." },
    { year: "1990", title: "Ulysses launched", detail: "The NASA and ESA probe uses a Jupiter flyby to swing over the Sun's poles, the first spacecraft to sample the solar wind at high latitudes." },
    { year: "1995", title: "SOHO begins its watch", detail: "The ESA and NASA Solar and Heliospheric Observatory begins three decades of uninterrupted observation from the L1 point." },
    { year: "2010", title: "Solar Dynamics Observatory", detail: "NASA's SDO starts returning ultra-high-definition images of the Sun every few seconds in multiple wavelengths." },
    { year: "2018", title: "Parker Solar Probe launched", detail: "The first mission designed to fly through the corona sets off, protected by a carbon-composite heat shield." },
    { year: "2020", title: "Solar Orbiter launched", detail: "ESA's spacecraft begins a series of Venus flybys that will tilt its orbit to view the Sun's poles." },
    { year: "2021", title: "Parker 'touches' the Sun", detail: "On 28 April 2021 Parker Solar Probe crosses the Alfvén surface, becoming the first spacecraft to enter the corona." },
    { year: "2024", title: "Closest approach ever", detail: "On 24 December Parker passes 6.1 million km from the photosphere at about 690,000 km/h; a G5 geomagnetic storm in May lights up auroras worldwide." },
    { year: "2025", title: "First view of the Sun's poles", detail: "Solar Orbiter images the south pole from 17° below the ecliptic, revealing a tangled magnetic field at solar maximum." },
    { year: "2026", title: "Missions press on", detail: "Parker completes its 29th perihelion on 4 September and is extended into 2029; Solar Orbiter's Venus flyby on 24 December tilts its orbit to 24° for even better polar views." },
  ],
  comparisons: [
    { label: "Diameter", value: 1392680, earth: 12742, unit: "km" },
    { label: "Mass", value: 333000, earth: 1, unit: "× Earth" },
    { label: "Surface gravity", value: 274, earth: 9.81, unit: "m/s²" },
    { label: "Rotation period (sidereal, mid-latitude)", value: 609.6, earth: 23.93, unit: "hours" },
    { label: "Surface temperature", value: 5505, earth: 15, unit: "°C" },
    { label: "Escape velocity", value: 617.7, earth: 11.19, unit: "km/s" },
    { label: "Mean density", value: 1.41, earth: 5.51, unit: "g/cm³" },
    { label: "Volume", value: 1300000, earth: 1, unit: "× Earth" },
  ],
  moons: [],
  quiz: [
    {
      prompt: "Roughly how long does energy released in the Sun's core take to reach the surface?",
      options: ["8 minutes", "About a year", "Around 100,000 years", "Several billion years"],
      answer: "Around 100,000 years",
      explanation: "Photons in the dense radiative zone are absorbed and re-emitted so many times that their random walk to the surface takes on the order of 100,000 years (estimates range from tens of thousands to about 170,000 years). The final trip to Earth then takes just 8 minutes.",
    },
    {
      prompt: "Which layer of the Sun is hotter than the visible surface, despite being further from the core?",
      options: ["The radiative zone", "The corona", "The photosphere", "The convective zone"],
      answer: "The corona",
      explanation: "The corona exceeds 1 million °C while the photosphere is about 5,500 °C. This 'coronal heating problem' is a key target of Parker Solar Probe and Solar Orbiter.",
    },
    {
      prompt: "What was the first spacecraft to fly through the Sun's corona?",
      options: ["SOHO", "Ulysses", "Solar Orbiter", "Parker Solar Probe"],
      answer: "Parker Solar Probe",
      explanation: "Parker Solar Probe crossed into the corona in April 2021 and, in December 2024, passed within 6.1 million km of the Sun's surface.",
    },
    {
      prompt: "Why do sunspots look dark?",
      options: [
        "They are holes into the cooler interior",
        "They are cooler than the surrounding surface because magnetic fields suppress convection",
        "They are clouds of soot from the corona",
        "They are shadows cast by Mercury",
      ],
      answer: "They are cooler than the surrounding surface because magnetic fields suppress convection",
      explanation: "Sunspots are around 3,500 °C compared with 5,500 °C for the photosphere. They only look dark by contrast; alone, a sunspot would outshine the full Moon.",
    },
    {
      prompt: "What will the Sun eventually become after its red-giant phase?",
      options: ["A neutron star", "A black hole", "A white dwarf", "A brown dwarf"],
      answer: "A white dwarf",
      explanation: "The Sun is not massive enough to explode as a supernova. After shedding its outer layers as a planetary nebula it will leave an Earth-sized white dwarf that slowly cools.",
    },
  ],
  glossary: [
    { term: "Nuclear fusion", definition: "The process in which light atomic nuclei (here hydrogen) combine to form heavier ones (helium), releasing energy." },
    { term: "Photosphere", definition: "The thin, visible 'surface' of the Sun, about 5,500 °C, where the gas becomes transparent enough for light to escape." },
    { term: "Corona", definition: "The Sun's outer atmosphere, tenuous but heated to over 1 million °C, visible to the eye only during a total solar eclipse." },
    { term: "Solar wind", definition: "A continuous stream of charged particles flowing out of the corona at hundreds of kilometres per second." },
    { term: "Coronal mass ejection (CME)", definition: "A huge eruption of magnetised plasma from the Sun that can trigger geomagnetic storms if it strikes Earth." },
    { term: "Solar cycle", definition: "The roughly 11-year rise and fall in sunspot numbers and solar activity driven by the Sun's magnetic field reversing." },
    { term: "Main sequence", definition: "The long, stable phase of a star's life during which it fuses hydrogen in its core. The Sun is about halfway through it." },
    { term: "Helioseismology", definition: "The study of the Sun's interior using sound waves that make its surface oscillate with periods of about five minutes." },
  ],
  sources: [
    { title: "NASA Sun Fact Sheet", url: "https://nssdc.gsfc.nasa.gov/planetary/factsheet/sunfact.html" },
    { title: "NASA Science: The Sun", url: "https://science.nasa.gov/sun/" },
    { title: "NASA Science: Parker Solar Probe", url: "https://science.nasa.gov/mission/parker-solar-probe/" },
    { title: "ESA: Solar Orbiter gets world-first views of the Sun's poles", url: "https://www.esa.int/Science_Exploration/Space_Science/Solar_Orbiter/Solar_Orbiter_gets_world-first_views_of_the_Sun_s_poles" },
    { title: "NOAA Space Weather Prediction Center", url: "https://www.swpc.noaa.gov/" },
  ],
};
